export interface Question {
	text: string;
	answer: string;
	options: string[];
}

/* Some questions generated by ChatGPT */
const QUESTIONS: Question[] = [
	{
		text: "Qual foi o primeiro computador pessoal a ser lançado no mercado?",
		answer: "Altair 8800",
		options: ["IBM PC", "Apple I", "Altair 8800", "Commodore PET"],
	},
	{
		text: "Qual linguagem de programação é conhecida por seu uso em desenvolvimento web e por ser a linguagem de script do navegador?",
		answer: "JavaScript",
		options: ["Python", "C++", "Ruby", "JavaScript"],
	},
	{
		text: "Quem é conhecido como o pai da computação moderna?",
		answer: "Alan Turing",
		options: ["Charles Babbage", "Bill Gates", "Alan Turing", "Steve Jobs"],
	},
	{
		text: "O que a sigla “HTML” representa?",
		answer: "HyperText Markup Language",
		options: [
			"HyperText Markup Language",
			"High-Level Technical Model",
			"HyperText Machine Language",
			"High Tech Markup Language",
		],
	},
	{
		text: "Quem formulou a teoria da relatividade?",
		answer: "Albert Einstein",
		options: [
			"Isaac Newton",
			"Nikola Tesla",
			"Albert Einstein",
			"Stephen Hawking",
		],
	},
	{
		text: "Qual elemento é usado como base para a maioria dos semicondutores?",
		answer: "Silício",
		options: ["Carbono", "Silício", "Ouro", "Cobre"],
	},
	{
		text: 'O que a sigla "www" em um endereço de internet representa?',
		answer: "World Wide Web",
		options: [
			"World Wide Web",
			"Web Wide World",
			"Wide Web World",
			"World Web Wide",
		],
	},
	{
		text: "Qual foi o primeiro animal a ser enviado ao espaço?",
		answer: "A cadela Laika",
		options: [
			"O macaco Albert",
			"A cadela Laika",
			"O rato Hector",
			"A tartaruga Zond 5",
		],
	},
	{
		text: "Qual é o elemento químico mais abundante no universo?",
		answer: "Hidrogênio",
		options: ["Oxigênio", "Carbono", "Hidrogênio", "Ferro"],
	},
	{
		text: "O que é um exoplaneta?",
		answer: "Um planeta fora do Sistema Solar",
		options: [
			"Um planeta anão",
			"Um planeta gasoso",
			"Um planeta fora do Sistema Solar",
			"Um planeta recém-descoberto",
		],
	},
	{
		text: "Quem inventou a lâmpada elétrica?",
		answer: "Thomas Edison",
		options: [
			"Nikola Tesla",
			"Alexander Graham Bell",
			"Thomas Edison",
			"James Watt",
		],
	},
	{
		text: "Qual é a unidade básica de informação em computação?",
		answer: "Bit",
		options: ["Byte", "Bit", "Baud", "Hertz"],
	},
	{
		text: "Qual elemento é usado em baterias de carros elétricos?",
		answer: "Lítio",
		options: ["Cádmio", "Níquel", "Chumbo", "Lítio"],
	},
	{
		text: "Quem foi a primeira pessoa a viajar ao espaço?",
		answer: "Yuri Gagarin",
		options: ["Neil Armstrong", "Yuri Gagarin", "John Glenn", "Buzz Aldrin"],
	},
	{
		text: "Qual é a velocidade da luz?",
		answer: "Aproximadamente 299.792.458 metros por segundo",
		options: [
			"Aproximadamente 100.000 quilômetros por segundo",
			"Aproximadamente 299.792.458 metros por segundo",
			"Aproximadamente 1 milhão de quilômetros por hora",
			"Aproximadamente 500.000 metros por segundo",
		],
	},
	{
		text: "Qual é o maior planeta do Sistema Solar?",
		answer: "Júpiter",
		options: ["Saturno", "Júpiter", "Urano", "Netuno"],
	},
	{
		text: "Qual é a principal fonte de energia do Sol?",
		answer: "Fusão nuclear",
		options: [
			"Fissão nuclear",
			"Reações químicas",
			"Fusão nuclear",
			"Energia geotérmica",
		],
	},
	{
		text: "O que é um algoritmo?",
		answer:
			"Um conjunto de instruções passo a passo usadas para realizar uma tarefa",
		options: [
			"Um componente de hardware de computador",
			"Um tipo de vírus de computador",
			"Um conjunto de instruções passo a passo usadas para realizar uma tarefa",
			"Um programa de software avançado",
		],
	},
	{
		text: "Qual é a teoria que sugere que o universo está se expandindo?",
		answer: "Teoria do Big Bang",
		options: [
			"Teoria da Relatividade",
			"Teoria do Estado Estacionário",
			"Teoria da Evolução",
			"Teoria do Big Bang",
		],
	},
	{
		text: "O que é um algoritmo de ordenação?",
		answer: "Um método para organizar elementos em uma sequência específica",
		options: [
			"Um processo para eliminar erros de software",
			"Um método para organizar elementos em uma sequência específica",
			"Uma técnica para melhorar a segurança dos dados",
			"Um algoritmo que prevê resultados com base em dados de entrada",
		],
	},
	{
		text: "Qual é o propósito do HTML na construção de websites?",
		answer: "Estruturar e organizar o conteúdo da página",
		options: [
			"Processar e analisar dados do servidor",
			"Estruturar e organizar o conteúdo da página",
			"Gerar gráficos e animações interativas",
			"Conectar o site a bancos de dados",
		],
	},
	{
		text: "O que significa a sigla CSS em desenvolvimento web?",
		answer: "Cascading Style Sheets",
		options: [
			"Computer System Security",
			"Cascading Style Sheets",
			"Creative Software Solutions",
			"Central Storage System",
		],
	},
	{
		text: 'Qual é o conceito de "Herança" em programação orientada a objetos?',
		answer: "Uma classe pode herdar características de outra classe",
		options: [
			"Uma função pode operar em vários tipos de dados",
			"Dados podem ser transmitidos de um usuário para outro",
			"Uma classe pode herdar características de outra classe",
			"Um objeto pode ser copiado várias vezes",
		],
	},

	{
		text: "O que significa a sigla API em tecnologia?",
		answer: "Interface de Programação de Aplicações",
		options: [
			"Associação de Profissionais de Internet",
			"Análise Preditiva Inteligente",
			"Interface de Programação de Aplicações",
			"Agência de Proteção da Informação",
		],
	},
	{
		text: "Qual linguagem de programação é conhecida por seu uso no desenvolvimento de sistemas operacionais?",
		answer: "C",
		options: ["Java", "Python", "C", "JavaScript"],
	},
	{
		text: "O que é Git?",
		answer: "Um sistema de controle de versão distribuído",
		options: [
			"Uma linguagem de programação",
			"Um sistema de controle de versão distribuído",
			"Um tipo de base de dados",
			"Um framework de desenvolvimento web",
		],
	},
	{
		text: 'Para que serve a função "main()" em C e C++?',
		answer: "Ponto de entrada de um programa",
		options: [
			"Gerenciar memória",
			"Conectar com bancos de dados",
			"Ponto de entrada de um programa",
			"Criar interfaces gráficas",
		],
	},
	{
		text: "O que é SQL?",
		answer: "Uma linguagem para gerenciar e manipular bancos de dados",
		options: [
			"Um protocolo de segurança de internet",
			"Uma linguagem para gerenciar e manipular bancos de dados",
			"Um tipo de algoritmo de compressão de dados",
			"Um padrão de codificação de caracteres",
		],
	},
	{
		text: "O que significa IDE no contexto de programação?",
		answer: "Ambiente de Desenvolvimento Integrado",
		options: [
			"Identificador de Dispositivos Eletrônicos",
			"Ambiente de Desenvolvimento Integrado",
			"Interface de Dados Eficiente",
			"Indicador de Desempenho do Equipamento",
		],
	},
	{
		text: "O que é um bug em programação?",
		answer: "Um erro ou falha em um programa de computador",
		options: [
			"Um tipo de malware",
			"Uma ferramenta de teste de software",
			"Um erro ou falha em um programa de computador",
			"Um recurso oculto em um software",
		],
	},
	{
		text: "O que é uma variável em programação?",
		answer:
			"Um espaço de armazenamento que pode conter dados que podem ser modificados durante a execução do programa",
		options: [
			"Uma instrução que se repete várias vezes",
			"Um erro comum em programas de computador",
			"Um tipo de estrutura de dados",
			"Um espaço de armazenamento que pode conter dados que podem ser modificados durante a execução do programa",
		],
	},
];

export { QUESTIONS };
